/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesServiceRouteImport } from './routes/services.$service'
import { Route as LocationsLocationRouteImport } from './routes/locations.$location'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServiceAreasServiceLocationRouteImport } from './routes/service-areas.$service.$location'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLocationRoute = LocationsLocationRouteImport.update({
  id: '/locations/$location',
  path: '/locations/$location',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasServiceLocationRoute =
  ServiceAreasServiceLocationRouteImport.update({
    id: '/service-areas/$service/$location',
    path: '/service-areas/$service/$location',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/$location': typeof LocationsLocationRoute
  '/services/$service': typeof ServicesServiceRoute
  '/blog/': typeof BlogIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/service-areas/$service/$location': typeof ServiceAreasServiceLocationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/$location': typeof LocationsLocationRoute
  '/services/$service': typeof ServicesServiceRoute
  '/blog': typeof BlogIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/service-areas/$service/$location': typeof ServiceAreasServiceLocationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/$location': typeof LocationsLocationRoute
  '/services/$service': typeof ServicesServiceRoute
  '/blog/': typeof BlogIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/service-areas/$service/$location': typeof ServiceAreasServiceLocationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/blog/$slug'
    | '/locations/$location'
    | '/services/$service'
    | '/blog/'
    | '/locations/'
    | '/services/'
    | '/service-areas/$service/$location'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/blog/$slug'
    | '/locations/$location'
    | '/services/$service'
    | '/blog'
    | '/locations'
    | '/services'
    | '/service-areas/$service/$location'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/blog/$slug'
    | '/locations/$location'
    | '/services/$service'
    | '/blog/'
    | '/locations/'
    | '/services/'
    | '/service-areas/$service/$location'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LocationsLocationRoute: typeof LocationsLocationRoute
  ServicesServiceRoute: typeof ServicesServiceRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServiceAreasServiceLocationRoute: typeof ServiceAreasServiceLocationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$location': {
      id: '/locations/$location'
      path: '/locations/$location'
      fullPath: '/locations/$location'
      preLoaderRoute: typeof LocationsLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$service/$location': {
      id: '/service-areas/$service/$location'
      path: '/service-areas/$service/$location'
      fullPath: '/service-areas/$service/$location'
      preLoaderRoute: typeof ServiceAreasServiceLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  BlogSlugRoute: BlogSlugRoute,
  LocationsLocationRoute: LocationsLocationRoute,
  ServicesServiceRoute: ServicesServiceRoute,
  BlogIndexRoute: BlogIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServiceAreasServiceLocationRoute: ServiceAreasServiceLocationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './entry/tanstack-router-virtual.ts'
import type { startInstance } from './entry/tanstack-start-virtual.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
